server:
  port: 8080




#
#server:
#port: 8080
#spring:
#datasource:
#driver-class-name: com.mysql.jdbc.Driver
#url: jdbc:mysql://localhost:3306/gson_work?characterEncoding=utf-8
#username: root
#password: 123456
#pagehelper:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/register?characterEncoding=utf-8
    username: root
    data-password: 123456
#helper-dialect: mysql